## Machine Learning With Python: Save And Load Trained Model

In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [7]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [9]:
model.coef_

array([135.78767123])

In [10]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [12]:
import pickle

In [19]:
with open('model_pickle', 'wb') as file:
    pickle.dump(model,file)

In [21]:
with open('model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [22]:
mp.coef_

array([135.78767123])

In [23]:
mp.intercept_

180616.43835616432

In [24]:
mp.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [33]:
import joblib  from joblib 

SyntaxError: invalid syntax (<ipython-input-33-e1e83960a43d>, line 1)

In [31]:
joblib.dump(model, 'model_joblib')

NameError: name 'joblib' is not defined