### Practice Problem on Numpy

#### Prob 1: Numpy 2D Array
Problem Statement:
GIven a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.

In [1]:
import numpy as np
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list_2d)
print(arr)
    
    

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Problem-2 : NumPy 0s and 1s
Problem Statement:
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1. Print the elements of array.

In [2]:
arr = np.zeros(10, dtype=int)
arr[4] =1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


#### Problem-3 : NumPy Inclusive
Problem Statement:
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.

In [8]:

arr = np.arange(9,50)
print(arr)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


####  Problem-4 : Identity Matrix
Problem Statement:
Create an integer identity matrix of size (5, 6).
Print the Numpy array

In [9]:
arr = np.eye(5,6,dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


#### Problem-5 : Cut the Rope
Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

In [11]:
arr = np.linspace(0,5,10)
print(arr)
for i in range(1, len(arr) - 1):
    print(round(arr[i],2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


#### Problem-7 : Non-Zero elements¶
Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.

In [2]:
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)
print(ind[0])


[0 1 4]


#### Problem-8 : Multiples of 3
Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array array([1,3, 5, 7, 9, 11, 13, 15, 17, 19])
Print the index of elements.

In [3]:
arr = np.arange(1,20,2)
ind = np.where(arr%3 == 0)
print(ind[0])

[1 4 7]


#### Problem-9 : Odd elements
Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.

In [4]:
arr = np.arange(1,11)
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


#### Problem-10 : Replace Max
Problem Statemnt:
Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.

In [5]:
arr = np.array([11,2,13,4,15,6,27,8,19])
arr[arr.argmax()] = 0
for i in arr :
    print(i)

11
2
13
4
15
6
0
8
19


#### Problem-11 : Negate Elements
Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.

In [6]:
arr = np.arange(1,11)
arr[2:8] = np.multiply(arr[2:8], -1)
for i in arr :
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


#### Problem-12 : Height
Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm. Print the Numpy array.

In [8]:
age = np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height = np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
index = np.where(height > 155)
for i in range(len(index[0])) :
    print(age[index[0][i]], height[index[0][i]])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


#### Problem-13 : Sort by column
Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
[[21 20 19 18 17]
[16 15 14 13 12]
[11 10 9 8 7]
[ 6 5 4 3 2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1

In [9]:
arr = np.arange(21,1,-1)
arr = arr.reshape(4,5)
print(arr[::-1])

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


#### Problem - 14 Killed in USA

### Assignment
Given file "terrorismData.csv" It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

#### Problem-1 : Terrorism Day
Problem Statement :
Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
Print count of NumberOFAttack as integer value.

In [7]:
file_obj = open('terrorismData.csv')
fie_data = file_obj.read(100)
fie_data

FileNotFoundError: [Errno 2] No such file or directory: 'terrorismData.csv'