# Numpy
1. Numpy means Numerical Python
2. Python's Linear Algebra library
3. Gives us multi dimensional (multi-dim) array




### Why do we need Numpy ?
1. Memory requirement: Numpy lists require less memory than Python ones, see below example.
2. Operations on Numpy list are faster than that on normal lists.
3. Numpy is more convenient and has wider functionality.

In [5]:
# Memory requirement: Numpy lists require less memory than Python ones, see below example.

import numpy as np

li_arr = [i for i in range(0, 100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
## Size of one element in numpy array
print(np_arr.itemsize)

## Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)

4
400


In [7]:
import sys

a = 10

## Size req of 1 element in list
print(sys.getsizeof(a))

## Size of 100 elements in list
print(sys.getsizeof(1) * len(li_arr))

28
2800


In [8]:
import numpy as np
import time

size = 100000

## Addd elements of array a and b

def addition_using_list():
    t1 = time.time() # Epoch time
    a = range(size)
    b = np.arange(size)
    c = [a[i] + b[i] for i in range(size)]
    t2 = time.time()
    return (t2 - t1)

def addtion_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return (t2 - t1)

t_list = addition_using_list()
t_numpy = addtion_using_numpy()

print('List = ', t_list * 1000) ## Time in Milliseconds
print('Numpy = ', t_numpy * 1000) ## Time in Milliseconds

List =  40.93122482299805
Numpy =  2.0377635955810547


## Why are Numpy arrays fast?
In Numpy Array operations take place in chunks rather than element wise.

For example in case of adding respective elements of two lists, the addition takes place in chunks and not one element at a time.

### What is vectorization?

"Vectorization" (simplified) is the process of rewriting a loop so that instead of processing a single element of an array N times, it processes (say) 4 elements of the array simultaneously N/4 times.

Source: https://stackoverflow.com/questions/1422149/what-is-vectorization

### How to create Numpy Arrays ?

In [9]:
import numpy as np # np becomes alias for numpy
#Syntax for numpy array -> np.array(arraylike, ..,)

a = [1,2,3]
b = np.array(a)

print(a)
print(type(b))

[1, 2, 3]
<class 'numpy.ndarray'>


In [10]:
a =[1,2,3,'5', 'a']
b = np.array(a) # Numpy array can contain only homogenous elements ie elements of same type
# Hence here each element converts to string

print(b)

['1' '2' '3' '5' 'a']


In [11]:
a = [1, 2, 3, '5']
b = np.array(a, dtype = int) # We can specify the data-type for the numpy array elements

print(b)

[1 2 3 5]


In [12]:
a = [1, 2, 3, '5']

b = np.array(a*3) # A numpy array with 3 copies

print(b)

['1' '2' '3' '5' '1' '2' '3' '5' '1' '2' '3' '5']


In [13]:
b = np.ones(3)
b

array([1., 1., 1.])

In [14]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [15]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [16]:
b = np.zeros(3, dtype = int)
b


array([0, 0, 0])

In [17]:
b = np.empty(2)
b

array([4.24399158e-314, 1.06099790e-313])

### 2 D Array

In [18]:
b = np.ones((2, 4), dtype =int)
b


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
b = np.full(3, 5)
b

array([5, 5, 5])

In [20]:
b = np.full(3, 5, dtype = float)
b


array([5., 5., 5.])

In [21]:
b = np.full((3,4), 5)
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Q. Create an integer array of size 10, where all the values should be 0 but the fifth value be 1.

In [22]:
import numpy as np
x = np.zeros(10)
print(x)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## numpy.arange
#### numpy.arange([start, ]stop, [step, ]dtype=None)

Return evenly spaced values within a given interval. Values are generated within the half-open interval [start, stop).

For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list. When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.

### Parameters

#### start : number, optional

Start of interval. The interval includes this value. The default start value is 0.

#### stop : number

End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

#### step : number, optional

Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

#### dtype : dtype

The type of the output array. If dtype is not given, infer the data type from the other input arguments.

#### Returns

#### arange : ndarray

Array of evenly spaced values.

For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.